### ISSUE TITLE
Add project title to top of note

### ISSUE THREAD

**Issue by alltheseas** [gourcetools/nostr-commits#2]
Currently only the commit name, and the commit URL is added to the nostr-commits automated nostr note.

Requesting you add the project name as the first line of the nostr note. 

If implemented note should read:
Project name
Commit title
Github URL

In case of the below example, there would be a new first line of the nostr note that reads "Iris Messenger"

![image](https://user-images.githubusercontent.com/64376233/230939702-c4951171-2538-416e-bbb6-7687e66b7dbc.jpeg)

Origin: 

https://damus.io/note15r6dfu40jd80ls9y2836pcjh5fymmg7vh70f6ue5jtn83kdpn3rsnkultg

**Comment by gourcetools** [comment]
Yeah i see what you mean...
You would like:
```
username/repo-title
commit name
commit url
```

?

Well, the bot used to publish the name or the repo, B
ut i've removed it since it's already in the URL. 

I'd like to make it programmable with a little shell menu that let you set:
"Message content:
- author yes/no
- commit name
- commit date
- commit id
- repo
- repo url 
 and so on...




For now, https://nostr.band/npub1qqqqqhu87ep5rssjejfadsnxcqaww5kqyesw0znd59py77c9c3cqfec28r will keep pushing messages as they are for now. to keep it compact. I  have to work on this so it's easy to run and configure for anybody... i'm sorry.

**Comment by gourcetools** [comment]
check-commits.js already save this stuff, you can edit the nostril command to change the message, you also need to import variables. i will work on this later this month...

check-commits.js
```
    // Output the information to files
    fs.writeFileSync("./REPO-TITLE.txt", repoTitle);
    fs.writeFileSync("./REPO-URL.txt", repoUrl);
    fs.writeFileSync("./COMMIT-NAME.txt", commitName);
    fs.writeFileSync("./COMMIT-ID.txt", commitId);
    fs.writeFileSync("./COMMIT-URL.txt", commitUrl);
}
```

**Comment by alltheseas** [comment]
> repo-title
> 
> commit name
> 
> commit url

Above. Right now flow is user sees nostr commit, sees commit name, and then has to search for which project this is in the hyperlink or the github preview, which adds friction for nostr-commit note readers.

**Comment by gourcetools** [comment]
Ok, i've updated it. Thanks for the idea. ... what do you think of this?
![image](https://user-images.githubusercontent.com/120996278/230946114-3b298ae4-40d8-42b1-bed0-a798c28a3704.png)

https://github.com/gourcetools/nostr-commits/commit/13969b8a6f5c44cc6f04220e2cb2bbc74f00124d

**Comment by alltheseas** [comment]
👍
